version = 1

exclude_patterns = ["third_party/**"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "clang-format"