# Generated by Django 4.2.21 on 2025-05-22 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='默认: 192.168.1.121', max_length=20, verbose_name='摄像头IP地址')),
                ('resolution', models.CharField(choices=[('1920x1080', '1920x1080'), ('1280x720', '1280x720'), ('640x480', '640x480')], default='1920x1080', max_length=20, verbose_name='分辨率')),
                ('framerate', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='帧率 (FPS)')),
                ('stream_protocol', models.CharField(choices=[('rtmp', 'RTMP'), ('hls', 'HLS'), ('webrtc', 'WebRTC')], default='rtmp', max_length=10, verbose_name='推流协议')),
                ('stream_bitrate', models.CharField(default='4000k', help_text='例如: 2000k, 4M', max_length=20, verbose_name='视频码率')),
                ('auto_start', models.BooleanField(default=True, help_text='系统启动时自动运行摄像头服务', verbose_name='开机自启')),
                ('log_level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('error', 'ERROR')], default='info', max_length=10, verbose_name='日志级别')),
            ],
            options={
                'verbose_name': '摄像头全局配置',
                'verbose_name_plural': '摄像头全局配置',
            },
        ),
    ]
