# Generated by Django 4.2.21 on 2025-05-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfig',
            name='ip_address',
            field=models.CharField(default='192.168.0.121', help_text='默认: 192.168.1.121', max_length=20, verbose_name='摄像头IP地址'),
        ),
    ]
