# Generated by Django 4.2.21 on 2025-05-26 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraSettings', '0002_alter_cameraconfig_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='auto_exposure',
            field=models.BooleanField(default=True, help_text='启用自动曝光后将隐藏手动曝光调节', verbose_name='自动曝光'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='exposure_value',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='曝光值'),
        ),
    ]
