# Generated by Django 4.2.21 on 2025-07-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraSettings', '0003_cameraconfig_auto_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='data_mode',
            field=models.CharField(choices=[('udp', 'UDP 输出'), ('tcp_server', 'TCP 请求响应模式')], default='udp', help_text='选择数据推送方式：UDP广播 或 TCP请求-响应模式', max_length=20, verbose_name='数据推送模式'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='tcp_host',
            field=models.CharField(default='0.0.0.0', help_text='仅当选择TCP模式时生效', max_length=50, verbose_name='TCP监听地址'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='tcp_port',
            field=models.PositiveIntegerField(default=8888, help_text='仅当选择TCP模式时生效', verbose_name='TCP监听端口'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='udp_host',
            field=models.CharField(default='192.168.0.92', help_text='仅当选择UDP模式时生效', max_length=50, verbose_name='UDP发送地址'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='udp_port',
            field=models.PositiveIntegerField(default=9999, verbose_name='UDP发送端口'),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='udp_send_rate',
            field=models.PositiveIntegerField(default=5, help_text='仅当选择UDP模式时生效', verbose_name='UDP发送频率'),
        ),
    ]
